### ISSUE TITLE
Android app crash in background

### ISSUE THREAD

**Issue by strikeentco** [defold/extension-push#4] opened 2019-08-21 23:01 UTC
App crashed in background when receiving push that was sended with latest Firebase API.
Legacy variant from [Defold manual](https://www.defold.com/manuals/push/#_android_setup) works well.

Tested with Defold versions: 1.2.159, 1.2.160.
Tested on Samsung Galaxy S10 (Android 9), LG Nexus 5 (Android 6).

Can be reproduced with:
- https://www.npmjs.com/package/firebase-admin
- https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send
- Test message from https://console.firebase.google.com

Logcat:
```
08-19 22:13:07.349 27697 27838 E AndroidRuntime: FATAL EXCEPTION: Firebase-FirebaseMessagingService
08-19 22:13:07.349 27697 27838 E AndroidRuntime: Process: com.example.todo, PID: 27697
08-19 22:13:07.349 27697 27838 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/messaging/R$string;
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at com.google.firebase.messaging.zza.zzh(Unknown Source:165)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source:57)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at com.google.firebase.iid.zzg.run(Unknown Source:4)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.R$string" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.todo-0xL9O0ZR-Afd2lJNbMf4cA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.todo-0xL9O0ZR-Afd2lJNbMf4cA==/lib/arm64, /data/app/com.example.todo-0xL9O0ZR-Afd2lJNbMf4cA==/base.apk!/lib/arm64-v8a, /system/lib64]]
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-19 22:13:07.349 27697 27838 E AndroidRuntime: 	... 7 more
```

**Comment by britzl** [comment] 2019-08-22 05:36
Thanks. We'll look into it!

**Comment by britzl** [comment] 2020-10-21 09:16
Unable to reproduce with latest version of the extension. Closing.

**Closed by britzl** 2020-10-21 09:16 UTC
Labels: bug
